- name: Run the equivalent of "apt-get update"
  apt:
     update_cache: yes
  become: true

- name: Create Minio group
  group:
    name: minio
    state: present
  become: true

- name: Create Minio user
  user:
    name: minio
    group: minio
    system: "yes"
    shell: "/usr/sbin/nologin"
  become: true

- name: Create the Minio data storage directories
  file:
    path: "/mnt/data"
    state: directory
    owner: minio
    group: minio
    mode: 0750
  become: true

- name: Create config file for Minio
  file:
    path: "/etc/default/minio"
  become: true

- name: Add config settings
  blockinfile:
    dest: "/etc/default/minio"
    insertafter: EOF
    block: |
      MINIO_VOLUMES="/mnt/data"
      MINIO_OPTS="--console-address :9001"
      MINIO_ROOT_USER=minioadmin123
      MINIO_ROOT_PASSWORD=minioadmin123
  become: true

- name: Download Minio
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio_20241013133411.0.0_amd64.deb
    dest: ~/

- name: Install Minio
  shell: "dpkg -i minio_20241013133411.0.0_amd64.deb"
  become: true

- name: Start Minio
  shell: "systemctl start minio"
  become: true
