---
- hosts: BPC
  tasks:
  - name: User Create for sp-user
    ansible.builtin.user:
      name: sp-user
      comment: user for spark
      createhome: yes
      home: /home/sp-user
      shell: /bin/bash
  - name: Upload/copy the keys
    authorized_key:
           user: sp-user
           state: present
           manage_dir: yes
           key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
