# export ANSIBLE_HOST_KEY_CHECKING=False
# apt update
- name: Run the equivalent of "apt-get update"
  apt:
     update_cache: yes
  become: true

- name: Java install
  shell: "apt install openjdk-8-jdk -y"
  become: true

- name: Scala install
  shell: "apt-get install scala -y"
  become: true

- name: Create sp-user
  user:
    name: sp-user
    password: "{{ '123' | password_hash('sha512') }}"
    shell: /bin/bash
    state: present
  become: true

- name: Add user to sudo group
  user:
    name: username
    groups: sudo
    append: yes
  become: true

- name: Allow passwordless sudo for the user
  blockinfile:
    dest: "/etc/sudoers"
    insertafter: EOF
    block: |
      # environment variable exports
      sp-user ALL=(ALL:ALL) ALL
      sp-user ALL=(ALL:ALL) NOPASSWD: ALL
  become: true

#- name: Download Spark
#  ansible.builtin.get_url:
#    url: https://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
#    dest: /home/student

#- name: Unzip Spark
#  shell: "tar xvf spark-3.1.1-bin-hadoop3.2.tgz"
#  become: true

#- name: Create home dir for Spark
#  shell: "mv spark-3.1.1-bin-hadoop3.2 /home/sp-user/spark"
#  become: true

- name: append environment variables to the end of .bashrc file
  blockinfile:
    dest: "/home/sp-user/.bashrc"
    insertafter: EOF
    block: |
      # environment variable exports
      export PATH="$PATH:/home/sp-user/spark/bin";
  become: true

- name: Save bashrc
  #shell: "source /home/sp-user/.bashrc"
  #action: shell source /home/sp-user/.bashrc
  #become: true
  shell: source /home/sp-user/.bashrc
  args:
    executable: /bin/bash
